sudo: required
dist: trusty
language: generic
compiler:
  - gcc
notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - yijiangh@mit.edu

env:
  global:
    - ROS_DISTRO=kinetic
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=choreo.rosinstall
    - NOT_TEST_INSTALL=true
    - BEFORE_SCRIPT='catkin config -w $CATKIN_WORKSPACE --no-install'
  matrix:
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - source .ci_config/travis.sh
