controller_list:
  - name: fake_manipulator_controller
    joints:
      - rail_to_robot_base_link
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_manipulator_tcp_controller
    joints:
      - rail_to_robot_base_link
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6