# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  linear_axis_actuation_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_a1:
    has_velocity_limits: true
    max_velocity: 2.68780704807
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_a2:
    has_velocity_limits: true
    max_velocity: 2.68780704807
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_a3:
    has_velocity_limits: true
    max_velocity: 3.97935069455
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_a4:
    has_velocity_limits: true
    max_velocity: 5.98647933434
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_a5:
    has_velocity_limits: true
    max_velocity: 6.70206432766
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_a6:
    has_velocity_limits: true
    max_velocity: 12.5838239069
    has_acceleration_limits: false
    max_acceleration: 0