controller_list:
  - name: fake_manipulator_controller
    joints:
      - robot_joint_1
      - robot_joint_2
      - robot_joint_3
      - robot_joint_4
      - robot_joint_5
      - robot_joint_6
  - name: fake_rail_robot_manipulator_controller
    joints:
      - linear_axis_actuation_joint
      - robot_joint_1
      - robot_joint_2
      - robot_joint_3
      - robot_joint_4
      - robot_joint_5
      - robot_joint_6